CRUDs for Models
rilindbicaj/SPMSFaculties pull request #2
Opened 2022-05-22 20:16 UTC by EndritMakolli

Create, Read, Update and Delete Methods and Controllers added for each Model

2022-05-23 08:48 UTC, rilindbicaj commented on API/Controllers/FacultiesController.cs
> +        private readonly IMediator _mediator;
This is not necessary. You're already inheriting the Mediator attribute from BaseController.

2022-05-23 09:18 UTC, rilindbicaj requested changes
- [x] Rewrite controllers - if a controller extends BaseController, they shouldn't need their own mediator - they already inherit one from BaseController. Remove all _mediator attributes and use the inherited Mediator from BaseController. Also, remove the constructors from the controllers. They're unnecessary.
- [x]  Use DTOs - And only add the necessary attributes to create the object. Navigation properties, such as "Major" and "FacultySemesters" are part of the domain model only. Also return response DTOs, not the entire model. Check SPMSPosts for examples.
- [x] Use Automapper - After implementing DTOs, use Automapper to map between them. 
- [x] Refactor redundant code - Automapper will handle the Edit methods, where most of the repeated code is.
- [x] Rename Application classes - Make the classes represent an actual use case instead of just Edit, Create, Delete.

2022-05-23 09:18 UTC, rilindbicaj commented on Application/Faculties/Create.cs
> +                var faculty = new Faculty
You've already provided a Faculty object, there's no need to create it again.

And again, navigation properties should not be included in request objects.

2022-05-23 09:18 UTC, rilindbicaj commented on Application/Faculties/Edit.cs
> +
Use automapper for this.

2022-05-30 12:01 UTC, merged

2022-10-11 09:00 UTC, EndritMakolli commented
Bic ti qr kap heki kta requesta, asnjana nuk o tu u bo inherit prej
basecontroller, ControllerBase so i njejti sen me BaseController, kshtuqe
osht e nevojshme me inherite qata, bone merge me main ma shpejt qet branch,
senet qe funsionojn munen mu ristrukturu edhe prej main edhe qe tdoket
najsen “unnecessary” ma shpejt ja bon delete se me ma shkru kete koment.

Me respekt Endriti

On Mon, 23 May 2022 at 10:49, rilindbicaj ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In API/Controllers/FacultiesController.cs
> <https://github.com/rilindbicaj/SPMSFaculties/pull/2#discussion_r879182665>
> :
>
> > +using System.Threading.Tasks;
> +using System.Collections.Generic;
> +using Domain;
> +using Application.Faculties;
> +using Microsoft.AspNetCore.Authorization;
> +
> +
> +namespace API.Controllers
> +{
> +    [AllowAnonymous]
> +    [Route("api/[controller]")]
> +    [ApiController]
> +
> +    public class FacultiesController :  ControllerBase
> +    {
> +        private readonly IMediator _mediator;
>
> This is not necessary. You're already inheriting the Mediator attribute
> from BaseController.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rilindbicaj/SPMSFaculties/pull/2#pullrequestreview-981362011>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASVHL4YXMFPGENDMNCHT22DVLNBAPANCNFSM5WT3ZFMA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-11 09:07 UTC, rilindbicaj commented
![image](https://user-images.githubusercontent.com/73657560/195047777-c9508e93-7594-4c6d-8070-ea8bd8946215.png)